### ISSUE TITLE
发现两个我觉得的代码风险

### ISSUE THREAD

**Issue by anjvW** [Carole007/carole-admin#4]
看了下代码，发现两个我觉得的代码风险

### 接口文档无鉴权

https://carole.top/v1/api#/

接口文档应该是管理员登录以后才能访问的。

### jwt密钥硬编码
jwt不应该是硬编码在代码中。
推荐：
    可以设置为随机字符串，保存在redis中

**Comment by Carole007** [comment]
首先，对于接口文档鉴权问题，你可以通过修改config.ts配置接口文档路径比如：/apidoc_key_xxx（这样就只有你知道了），或者选择关闭接口文档。
没有鉴权的原因是，可以在新页面直接打开查看，还可以分享别人一起查看。
其次，jwt并没有你说的这种问题。
